name: C# CI Pipeline with Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.100'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run tests and generate Allure results
      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory allure-results

      # Step 6: Install Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jre # Allure requires Java
          curl -o allure.tar.gz -L https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -xzf allure.tar.gz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      # Step 7: Verify Allure Installation
      - name: Verify Allure Installation
        run: allure --version

      # Step 8: Generate Allure Report
      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      # Step 9: Upload Allure Report as Artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/

  publish-report:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Serve Allure Report Locally (Optional)
      - name: Serve Allure Report (Optional)
        run: |
          allure open allure-report
